### ISSUE TITLE
Create a WPF based timer

### ISSUE THREAD

**Issue by jdhitsolutions** [jdhitsolutions/PSTimers#1]
It might be nice to have a few WPF-based timers, although they won't work on PowerShell Core.

**Comment by jdhitsolutions** [comment]
merging this issue with one from PSClock. https://github.com/jdhitsolutions/PSClock/issues/3

**Comment by RStadlmair** [comment]
Works great ! Thanks

**Comment by jdhitsolutions** [comment]
Added `Start-PSCountdownTimer` and `Stop-PSCountdownTimer` to v1.0.0
