### ISSUE TITLE
[Bug]: Use PSStyle for Progress style

### ISSUE THREAD

**Issue by jdhitsolutions** [jdhitsolutions/PSTimers#10]
### Describe the problem

Need to accommodate $PSStyle in PowerShell 7. Might also consider changing the view to classic.

### Expectation

Need to adjust colors when using the ProgressStyle parameter.

### PowerShell version

7.2

### Platform

Windows 11 Pro or Enterprise

### Additional Checks

- [X] You are using the latest version of this module.
- [X] You have read this repository's README file.
- [X] You have read full help and examples for the command you are having problems with.
- [X] You are running PowerShell in an elevated session.
- [X] You are running in a traditional PowerShell console or Windows Terminal

**Comment by jdhitsolutions** [comment]
May also have to include adjusting `$host.privatedata.progressforegroundcolor`.

**Comment by joshua-russell** [comment]
Maybe a switch param to toggle Progress.view **classic** and **minimal**?

**Comment by jdhitsolutions** [comment]
I had the same thought. My hesitation is that it would need to be a dynamic parameter, and I try to avoid them if I can. It is just as easy for the user to manually change the style before running the command. I have a help example that shows exactly that. When writing a function, It is always a balancing act between reducing friction in using the command and leaving some responsibility for the user.

**Comment by jdhitsolutions** [comment]
I've addressed this in v1.0.0.
