### ISSUE TITLE
[Bug]: Unable to run MyTimer - "Unable to find type [MyTimer]"

### ISSUE THREAD

**Issue by joshua-russell** [jdhitsolutions/PSTimers#11]
### Describe the problem

Trying Start-MyTimer - Line 4 of Start-MyTimer.ps1 errors: 
> Unable to find type [MyTimer].

Get-TypeData MyTimer reveals the type is registered but appears to be empty: 
| TypeName | Members |
|--- |--- |
| MyTimer | {} |

### Expectation

Expected MyTimer to start without error. 

### Additional Information

**PowerShell versions tested**: - 7.3.7; 7.3.3; 5.1
PSTimers Version 1.0.1
Running with executionPolicy in bypass

Is there a problem with mytimer.types.ps1xml? I looked at it but it seems fine. 

### PowerShell version

Other

### Platform

Windows 11 Pro or Enterprise

### Additional Checks

- [X] You are using the latest version of this module.
- [X] You have read this repository's README file.
- [X] You have read full help and examples for the command you are having problems with.
- [X] You are running PowerShell in an elevated session.
- [X] You are running in a traditional PowerShell console or Windows Terminal

**Comment by jdhitsolutions** [comment]
That's a simple fix. The `MyTimer` class is private.

**Comment by jdhitsolutions** [comment]
I've published v1.1.0 to the PowerShell Gallery, which should fix this. I also discovered the class definition was missing.

**Comment by joshua-russell** [comment]
Great - testing shortly.

**Comment by joshua-russell** [comment]
Working perfectly!
