### ISSUE TITLE
[Bug]: ProgressStyle Random - Invalid Operation

### ISSUE THREAD

**Issue by joshua-russell** [jdhitsolutions/PSTimers#8]
### Describe the problem

Line 219 generates an error: 
> InvalidOperation
> … $host.globalData.progressBackgroundColor = ($progcolors | …
> The property 'progressBackgroundColor' cannot be found on this object. Verify that the property exists and can be set.
While I'm not very familiar with how this code works, it seems that $host does not have a globalData - changing this line to $host.privateData seems to fix the issue in PSVersion 5.1 PSEdition Desktop

Note - color doesn't change in PSVersion 7.2.6 PSEdition Core.

### Expectation

Countdown to proceed without errors, changing the colors randomly in PowerShell console.

### Additional Information

Pull request with suggested change incoming. 

### PowerShell version

7.2

### Platform

Windows 10 Pro or Enterprise

### Additional Checks

- [X] You are using the latest version of this module.
- [X] You have read this repository's README file.
- [X] You have read full help and examples for the command you are having problems with.
- [X] You are running PowerShell in an elevated session.
- [X] You are running in a traditional PowerShell console or Windows Terminal

**Comment by jdhitsolutions** [comment]
I haven't used this module in a while, and I can see a number of issues, especially with PowerShell 7. I merged your PR. I'll close this for now.
